### ISSUE TITLE
output is not a list of commands

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-JordanHood#1]
You probably know this already, but the output seems to be some sort of debug output, rather than the solution to the problem.

I usually try to not commit versions that print the debug stuff. One way to do this is to have some global boolean variable called `debug` and make sure that you keep that set to `false` in the repository, although you might have it set to `true` in your local copy. Then, all debug prints would start with something like `if (debug) ...`

**Comment by JordanHood** [comment]
at the moment i have gone back and re-done my solution as it was getting a bit messy, ill be removing the debugging later on once i have gotten the code finished

**Comment by rgrig** [comment]
Hi Jordan,
The automated tests expect your program to print to standard output what you are currently saving in `commands.json`. If you look at the command used to run your solver (https://github.com/ukc-co663/depsolver/blob/master/tests/inside-test.sh#L26) you'll see that the output is redirected to `commands.json`. So, I believe there's a race condition here and you may or may not get lucky; or, otherwise put, you may get unlucky and the solution you write in `commands.json` may be ignored. So, just change the output to go to the console (https://github.com/ukc-co663/dependency-solver-JordanHood/blob/master/main.js#L7).

**Comment by JordanHood** [comment]
Hi @rgrig, yep i am aware that i am currently writing to a `commands.json` file as i was having issues logging the commands generated to the console as due to the way node logs `["a"]` (`['a']`) was breaking the judge script, ive found a fix to this and have changed the output to be to stdout now
