### ISSUE TITLE
dependencies flattening

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-JordanHood#2]
I don't understand the algorithm you plan to use for solving dependencies but, in package.js, there is a split that looks suspicious in `dependencies` and `conjunctions`. If I understand correctly, there are flat arrays (as in, they don't contain other arrays as elements). If that is the case, it seems difficult to handle all the cases.

So, (1) look at some tricky dependencies and (2) write down (for yourself) the algorithm you are planning to use.

For (1), here's an example: Suppose A requires (B or C) and also (D or E). Suppose further that C and D conflict, and B and E conflict, and A and E conflict. One valid state is [A,B,D]. Will it be found?

**Comment by JordanHood** [comment]
At the moment i'm reworking my original solution and i have yet to solve the optional dependencies for packages, im hoping to get it done over the weekend
